### ISSUE TITLE
Bg: addUsers school_uid

### ISSUE THREAD

**Issue by jamsgra** [chingu-voyages/v9-bears-team-21#14]
- Add school_uid to each new user

**Comment by sulenchy** [comment]
I think a better way to fix this is to allow the `admin` or the `super admin` to select the school he or she intends to add users to before uploading the file. Then during the process, the `school_uid` would be included in each of the records. What do you think?

**Comment by sulenchy** [comment]
@jamsgra What do you think concerning the above comment?
